# Generated by Django 5.0.4 on 2024-04-13 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='latitude')),
                ('height', models.IntegerField(verbose_name='latitude')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.URLField(verbose_name='image')),
                ('title', models.CharField(max_length=255, verbose_name='image title')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, choices=[('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б')], max_length=2, verbose_name='winter level')),
                ('spring', models.CharField(blank=True, choices=[('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б')], max_length=2, verbose_name='spring level')),
                ('summer', models.CharField(blank=True, choices=[('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б')], max_length=2, verbose_name='summer level')),
                ('autumn', models.CharField(blank=True, choices=[('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б')], max_length=2, verbose_name='autumn level')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='user id')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('fam', models.CharField(max_length=200, verbose_name='surname')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('otc', models.CharField(blank=True, max_length=200, verbose_name='patronymic')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=200, verbose_name='beauty title')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('other_titles', models.TextField(verbose_name='other titles')),
                ('connect', models.TextField(blank=True, verbose_name='connect')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='add time')),
                ('status', models.CharField(choices=[('new', 'Ожидает модерацию'), ('pending', 'Принято на модерацию'), ('accepted', 'Модерация пройдена успешно'), ('rejected', 'Модерация завершена, отклонено')], default='new', max_length=10, verbose_name='status')),
                ('coords_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pass_app.coords', verbose_name='coords')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pass_app.level', verbose_name='level')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pass_app.user', verbose_name='user id')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pass_app.image')),
                ('pereval_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pass_app.perevaladded')),
            ],
        ),
    ]
